### ISSUE TITLE
Operating system tabs don't render properly in the Prereqs page

### ISSUE THREAD

**Issue by Frijol** [tessel/t2-start#160]
**The problem:**

The page is http://tessel.github.io/t2-start/cmd.html

It looks like this:

![screen shot 2017-03-22 at 12 57 28 pm](https://cloud.githubusercontent.com/assets/454690/24218113/4dd3d0d0-0eff-11e7-996f-32b6b89622ca.png)

It should look and work the way it does on the [Install](http://tessel.github.io/t2-start/index.html) page:

![screen shot 2017-03-22 at 12 59 36 pm](https://cloud.githubusercontent.com/assets/454690/24218139/6c4fe27e-0eff-11e7-86ad-d9f711998e7e.png)

**To resolve this issue:**

From the files in https://github.com/tessel/t2-start

Find out what's different between the tabs in `cmd.md` and `install.md`.

Use the tabs on `install.md` as a model to fix the tabs on `cmd.md`.

(Hint: clone this repo and then follow [these instructions](https://github.com/tessel/t2-start#running-locally) to render the pages locally)

**Comment by yousifm** [comment]
It seems to render correctly when viewed using jekyll on my local clone

**Comment by rickMcGavin** [comment]
@Frijol It definitely displays correctly on the local server. I tried pushing it to my own repo, and it displays incorrectly like in the repo here. I'm not seeing any difference between install.md and cmd.md that's causing the issue.

I believe I did find the problem though. I analyzed the network requests in chrome dev tools. The issue seems to be that the install.js script isn't running when the cmd.html file loads on gh-pages, but it does load the install.js script on the local jekyll server. 

I believe this is further supported when you inspect the `<dl>` element locally, the nested tabs have been converted to `<dd>` elements. On gh-pages, they are `<a>` tags wrapped in a `<p>` tag as if the script never ran to convert them.

I cannot seem to figure out how to fix it so the install.js script runs when you load cmd.html on gh-pages though.

**Comment by reuben453** [comment]
For some reason the install.js script does not get included on the page when the script tag is placed in cmd.html. I moved it to the markdown file (cmd.md) and it now gets included. I also changed the dl element to be formed using kramdown syntax rather than html and text.

I've opened a PR for these changes: #162 
Let me know what you think.
