### ISSUE TITLE
Convert this into a Gitbook?

### ISSUE THREAD

**Issue by tcr** [tessel/t2-start#51]
This is a possibility, and gives us the benefit of depending on some open source (supported) code rather than our own concoction.

/cc @Frijol for thoughts

**Comment by Frijol** [comment]
Not sure what problem we're solving by converting this again.. but also not totally familiar with Gitbook. Also our page is pretty static, so maintenance is already pretty minimal.

What are the main points of this proposed change?

**Comment by tcr** [comment]
@Frijol not really converting (it's already markdown and in the right structure) but basically removing our hacky JS gen script and just using Gitbook's framework instead. Might need to write a plugin script, but that's it.

Would probably be pretty simple to port over, but it makes it less of a barrier to entry for people familiar with that structure to contribute.

(@jiahuang's idea)

**Comment by Frijol** [comment]
ah I see. Sure, sounds good to me

**Comment by Frijol** [comment]
this would fix e.g. the code fences not working, yes?

**Comment by Frijol** [comment]
I just investigated, and it's a massive pain to convert our current iteration of the start experience to gitbooks. The biggest problems are in styling, the tabs on the install page, and the multi-column layout on the module pages.

![screen shot 2016-09-03 at 2 23 33 pm](https://cloud.githubusercontent.com/assets/454690/18226980/811747e6-71e4-11e6-9ce3-10fda5f19fe2.png)

Closing, since I don't think this is all that useful for the difficulty caused.
