### ISSUE TITLE
Clean up Linux tab of Command Line Basics

### ISSUE THREAD

**Issue by flaki** [tessel/t2-start#56]
The Linux tab at the [Command Line Basics](http://tessel.github.io/t2-start/cmd.html) page uses Mac descriptions, but Windows command line screenshots, this should get its proper, linux/unix-based  instructions.

**Comment by brihijoshi** [comment]
Hi, Please assign this issue to me. I've started working on it.

**Comment by Frijol** [comment]
Thanks @brihijoshi! Convention for Tessel is usually to open a PR with "not ready" or "don't merge" somewhere in the title as you begin work and link to it in the issue. That lets us see the work developing– and is useful in the structure of an open source project, because it would let someone else pick up where you left off if you (as a contributor) were to suddenly disappear with the work partially complete (this happens a lot in open source).
Then, when the PR is ready, take "don't merge" out of the title and ask for a review!

This information feels like something that might belong in the CONTRIBUTING.md document, can you make an issue on tessel/project please?

**Comment by brihijoshi** [comment]
Thanks a lot for that info! On it. Making the issue.
